"""
main.py  –  Finance House Dubai · Gold Loan API

Start:
    uvicorn main:app --reload --port 8000

Docs:
    http://localhost:8000/docs
"""

import sys
import json
import logging
import time
import uuid
from contextvars import ContextVar
from pathlib import Path

# Make sure sibling packages resolve correctly
sys.path.insert(0, str(Path(__file__).parent))

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware

_request_id_ctx: ContextVar[str] = ContextVar("request_id", default="")

class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload = {
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(record.created)),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
            "request_id": _request_id_ctx.get() or None,
        }
        if record.exc_info:
            payload["exc_info"] = self.formatException(record.exc_info)
        return json.dumps(payload, ensure_ascii=False)

logger = logging.getLogger("gold-loan-api")
if not logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(JsonFormatter())
    logger.addHandler(_handler)
logger.setLevel(logging.INFO)

from models import (
    LoanCalculationRequest,
    LoanCalculationResponse,
    LiveGoldPriceResponse,
    TodayGoldLoanScoreResponse,
    CustomerProfile,
    LoanHistoryOverview,
)
from services.gold_service import (
    fetch_live_gold_price_aed,
    fetch_live_gold_price_aed_karats,
    build_gold_insights,
)
from services.customer_service import get_customer_profile, get_loan_history
from services.loan_calculator import calculate_ltv_and_loan
from services.risk_analyzer import build_risk_insights
from services.uaepass_service import fetch_uaepass_profile


# ── App setup ──────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Finance House Dubai – Gold Loan API",
    description=(
        "Backend for the Gold Loan Valuation & Eligibility Dashboard.\n\n"
        "**Quick start:**\n"
        "1. Run `python seed_data.py` to generate dummy customer data.\n"
        "2. `uvicorn main:app --reload`\n"
        "3. POST `/loan/calculate` with a valid Emirates ID.\n\n"
        "**Sample Emirates IDs** (generated by seed script):\n"
        "- `784-1985-1234567-1` (Ahmed Al-Mansoori, CIBIL 780, A+)\n"
        "- `784-1990-2345678-2`\n"
        "- `784-1978-3456789-3`"
    ),
    version="1.0.0",
)

@app.middleware("http")
async def request_context_middleware(request: Request, call_next):
    request_id = request.headers.get("x-request-id") or request.headers.get("x-correlation-id") or str(uuid.uuid4())
    token = _request_id_ctx.set(request_id)
    start = time.perf_counter()
    logger.info(f"[tomo-id-007] request.start")
    try:
        response = await call_next(request)
    finally:
        duration_ms = (time.perf_counter() - start) * 1000.0
        logger.info(f"[tomo-id-008] request.end duration_ms={duration_ms:.2f} method={request.method} path={request.url.path}")
        _request_id_ctx.reset(token)

    response.headers["x-request-id"] = request_id
    return response

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Health ─────────────────────────────────────────────────────────────────────

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from fastapi.responses import Response

REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "path", "status"],
)
REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "path"],
)

@app.middleware("http")
async def prometheus_middleware(request: Request, call_next):
    start = time.perf_counter()
    response = await call_next(request)
    duration_s = time.perf_counter() - start
    REQUEST_LATENCY.labels(request.method, request.url.path).observe(duration_s)
    REQUEST_COUNT.labels(request.method, request.url.path, str(response.status_code)).inc()
    return response

@app.get("/metrics", tags=["System"], include_in_schema=False)
async def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)

@app.get("/health", tags=["System"])
async def health():
    return {"status": "ok", "service": "Finance House Dubai Gold Loan API"}


# ── Gold price ─────────────────────────────────────────────────────────────────

from fastapi.responses import JSONResponse

@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    ref_id = _request_id_ctx.get() or str(uuid.uuid4())
    logger.error(f"[tomo-id-011] unhandled_exception path={request.url.path} ref_id={ref_id}", exc_info=exc)
    return JSONResponse(
        status_code=500,
        content={
            "code": "ERR_INTERNAL",
            "message": "Unexpected server error while processing request.",
            "action": "Retry later. If the issue persists, contact support with the reference id.",
            "ref_id": ref_id,
        },
    )

@app.get(
    "/gold/price",
    response_model=LiveGoldPriceResponse,
    tags=["Gold"],
    summary="Fetch live gold price in AED per gram",
)
async def live_gold_price():
    """
    Fetches the current XAU price from gold-api.com and converts to AED/gram.
    Falls back to a cached value if the external API is unavailable.
    """
    karats, rate_24k, usd_per_oz, updated_at = await fetch_live_gold_price_aed_karats()
    return LiveGoldPriceResponse(
        currency="AED",
        rate_24k_per_gram=rate_24k,
        karats=karats,
        price_usd_per_oz=usd_per_oz,
        updated_at=updated_at,
    )


@app.get("/api/gold-rate/live", tags=["Gold"], summary="Live Saudi gold rates by karat")
async def live_gold_rate_by_karat():
    """
    Returns live UAE gold prices in AED per gram for multiple karats.
    """
    karats, rate_24k, _, _ = await fetch_live_gold_price_aed_karats()
    return {
        "country": "UAE",
        "currency": "AED",
        "unit": "g",
        "conversion": "XAU/USD per oz -> USD per gram -> AED per gram",
        "karats": karats,
        "rate24k": karats["24K"] if "24K" in karats else rate_24k,
    }


def _build_today_gold_loan_score(predicted_change_pct: float) -> TodayGoldLoanScoreResponse:
    pct = float(predicted_change_pct)

    if pct >= 5:
        score = min(10.0, 8.0 + min((pct - 5.0) / 5.0, 1.0) * 2.0)
        return TodayGoldLoanScoreResponse(
            score=round(score, 1),
            label="EXCELLENT TIME",
            market_condition="Predicted rise >= 5%",
            guidance="Urgency — act now",
            tone="Urgent and confident",
            predicted_change_pct=round(pct, 2),
        )

    if pct >= 2:
        score = 6.0 + ((pct - 2.0) / 3.0) * 1.9
        return TodayGoldLoanScoreResponse(
            score=round(score, 1),
            label="GOOD TIME",
            market_condition="Predicted rise 2–5%",
            guidance="Positive, encouraging",
            tone="Positive and supportive",
            predicted_change_pct=round(pct, 2),
        )

    if pct >= -2:
        score = 4.0 + ((pct + 2.0) / 4.0) * 1.9
        return TodayGoldLoanScoreResponse(
            score=round(score, 1),
            label="STABLE MARKET",
            market_condition="Predicted change ±2%",
            guidance="Neutral, honest",
            tone="Neutral",
            predicted_change_pct=round(pct, 2),
        )

    if pct >= -8:
        score = 2.0 + ((pct + 8.0) / 6.0) * 1.9
        return TodayGoldLoanScoreResponse(
            score=round(score, 1),
            label="WAIT IF YOU CAN",
            market_condition="Predicted drop 2–8%",
            guidance="Cautious but supportive",
            tone="Cautious",
            predicted_change_pct=round(pct, 2),
        )

    score = max(1.0, 1.9 - min((abs(pct) - 8.0) / 4.0, 0.9))
    return TodayGoldLoanScoreResponse(
        score=round(score, 1),
        label="POOR TIME",
        market_condition="Predicted drop > 8%",
        guidance="Honest + safety reassurance",
        tone="Conservative",
        predicted_change_pct=round(pct, 2),
    )


@app.get(
    "/api/gold-loan-score/today",
    response_model=TodayGoldLoanScoreResponse,
    tags=["Gold"],
    summary="ML-based timing score for gold loan action today",
)
async def today_gold_loan_score():
    """
    Converts ML predicted gold-price change into a 1–10 business score with
    guidance text for frontline officers.
    """
    insights = await build_gold_insights(12)
    logger.info(f"[tomo-id-010] gold_loan_score.prediction predicted_change_pct={float(insights.predicted_change_pct):.4f}")
    return _build_today_gold_loan_score(insights.predicted_change_pct)


# ── Customer lookup ────────────────────────────────────────────────────────────

@app.get(
    "/customer/{emirates_id}",
    response_model=CustomerProfile,
    tags=["Customer"],
    summary="Get customer profile by Emirates ID",
)
async def get_customer(emirates_id: str):
    """Returns profile for a known Emirates ID (from dummy dataset)."""
    profile = get_customer_profile(emirates_id)
    if profile is None:
        raise HTTPException(
            status_code=404,
            detail=f"No customer found for Emirates ID: {emirates_id}",
        )
    return profile


@app.get(
    "/customer/{emirates_id}/loans",
    response_model=LoanHistoryOverview,
    tags=["Customer"],
    summary="Get loan history for an Emirates ID",
)
async def get_customer_loans(emirates_id: str):
    """Returns full loan history overview including active/closed loans."""
    profile = get_customer_profile(emirates_id)
    if profile is None:
        raise HTTPException(status_code=404, detail=f"Unknown Emirates ID: {emirates_id}")
    return get_loan_history(emirates_id)


# ── Gold history + prediction ──────────────────────────────────────────────────

@app.get(
    "/gold/insights",
    tags=["Gold"],
    summary="Historical prices + future prediction for a given tenure",
)
async def gold_insights(
    tenure_months: int = Query(default=12, ge=1, le=36, description="Loan tenure in months"),
):
    """
    Returns 6-month historical gold prices (AED/g) and a polynomial-regression
    forecast for the requested tenure.
    """
    insights = await build_gold_insights(tenure_months)
    return insights


# ── Main calculation endpoint ──────────────────────────────────────────────────

@app.post(
    "/loan/calculate",
    response_model=LoanCalculationResponse,
    tags=["Loan"],
    summary="Calculate LTV, loan eligibility, and risk for a gold loan application",
)
async def calculate_loan(req: LoanCalculationRequest, request: Request):
    """
    Full pipeline:
    1. Fetch customer profile & loan history from Emirates ID
    2. Fetch live gold price
    3. Calculate gold valuation
    4. Compute LTV with all adjustment factors
    5. Predict gold price over the loan tenure
    6. Compute user & company risk scores
    7. Return a complete eligibility dashboard payload
    """

    # Simple in-memory rate limit (best-effort). For multi-instance prod, replace with Redis.
    client_ip = (request.client.host if request.client else "unknown")
    now = time.time()
    window_s = 60
    max_requests = 30

    if not hasattr(app.state, "rate_limit"):
        app.state.rate_limit = {}

    bucket = app.state.rate_limit.get(client_ip, [])
    bucket = [ts for ts in bucket if (now - ts) <= window_s]
    if len(bucket) >= max_requests:
        logger.warning(f"[tomo-id-009] rate_limit.exceeded ip={client_ip} window_s={window_s} max_requests={max_requests}")
        raise HTTPException(
            status_code=429,
            detail=(
                "Rate limit exceeded for loan calculation. "
                "Action: slow down requests and retry after 60s."
            ),
        )
    bucket.append(now)
    app.state.rate_limit[client_ip] = bucket

    # ── 1. Customer data ──────────────────────────────────────────────────────
    customer = get_customer_profile(req.emirates_id)
    if customer is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Emirates ID '{req.emirates_id}' not found in the system. "
                "Ensure seed_data.py has been run and the ID is correct."
            ),
        )
    history = get_loan_history(req.emirates_id)

    # ── 1b. Enrich with UAE PASS live identity (best-effort) ─────────────────
    uaepass = await fetch_uaepass_profile(req.emirates_id)
    if uaepass:
        customer = customer.model_copy(update={
            "customer_name": uaepass.get("fullnameEN") or customer.customer_name,
            "nationality":   uaepass.get("nationalityEN") or customer.nationality,
            "mobile":        uaepass.get("mobile") or customer.mobile,
            "gender":        uaepass.get("gender"),
            "email":         uaepass.get("email"),
            "full_name_ar":  uaepass.get("fullnameAR"),
            "nationality_ar": uaepass.get("nationalityAR"),
            "uaepass_verified": True,
        })

    # ── 2. Live AED karat rates (same source used by /api/gold-rate/live) ─────
    live_karats, _, _, _ = await fetch_live_gold_price_aed_karats()

    # ── 3. Gold insights (live AED price + history + prediction) ───────────────
    gold_insights = await build_gold_insights(req.tenure_months.value)

    # ── 4 & 5. LTV + eligibility calculation ─────────────────────────────────
    calc = calculate_ltv_and_loan(
        carat=req.carat,
        gold_type=req.gold_type,
        gold_weight_grams=req.gold_weight_grams,
        tenure_months=req.tenure_months.value,
        job_profession=req.job_profession,
        customer=customer,
        loan_history=history,
        gold_insights=gold_insights,
    )

    # ── 6. Risk analysis ──────────────────────────────────────────────────────
    risk = build_risk_insights(
        customer=customer,
        history=history,
        gold_insights=gold_insights,
        job_profession=req.job_profession.value,
        eligible_loan_aed=calc["eligible_loan_amount_aed"],
        ltv_pct=calc["recommended_ltv_pct"],
        tenure_months=req.tenure_months.value,
    )

    # ── 7. Assemble response ──────────────────────────────────────────────────
    return LoanCalculationResponse(
        **calc,
        customer_profile=customer,
        loan_history=history,
        gold_insights=gold_insights,
        risk_insights=risk,
        live_gold_currency="AED",
        live_gold_rates=live_karats,
    )


# ── Dev runner ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
