"""
main.py  –  Finance House Dubai · Gold Loan API

Start:
    uvicorn main:app --reload --port 8000

Docs:
    http://localhost:8000/docs
"""

import sys
from pathlib import Path

# Make sure sibling packages resolve correctly
sys.path.insert(0, str(Path(__file__).parent))

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from models import (
    LoanCalculationRequest,
    LoanCalculationResponse,
    LiveGoldPriceResponse,
    CustomerProfile,
    LoanHistoryOverview,
)
from services.gold_service import (
    fetch_live_gold_price_aed,
    fetch_live_gold_price_sar_karats,
    build_gold_insights,
)
from services.customer_service import get_customer_profile, get_loan_history
from services.loan_calculator import calculate_ltv_and_loan
from services.risk_analyzer import build_risk_insights
from services.uaepass_service import fetch_uaepass_profile


# ── App setup ──────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Finance House Dubai – Gold Loan API",
    description=(
        "Backend for the Gold Loan Valuation & Eligibility Dashboard.\n\n"
        "**Quick start:**\n"
        "1. Run `python seed_data.py` to generate dummy customer data.\n"
        "2. `uvicorn main:app --reload`\n"
        "3. POST `/loan/calculate` with a valid Emirates ID.\n\n"
        "**Sample Emirates IDs** (generated by seed script):\n"
        "- `784-1985-1234567-1` (Ahmed Al-Mansoori, CIBIL 780, A+)\n"
        "- `784-1990-2345678-2`\n"
        "- `784-1978-3456789-3`"
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Health ─────────────────────────────────────────────────────────────────────

@app.get("/health", tags=["System"])
async def health():
    return {"status": "ok", "service": "Finance House Dubai Gold Loan API"}


# ── Gold price ─────────────────────────────────────────────────────────────────

@app.get(
    "/gold/price",
    response_model=LiveGoldPriceResponse,
    tags=["Gold"],
    summary="Fetch live gold price in AED per gram",
)
async def live_gold_price():
    """
    Fetches the current XAU price from gold-api.com and converts to AED/gram.
    Falls back to a cached value if the external API is unavailable.
    """
    karats, rate_24k, usd_per_oz, updated_at = await fetch_live_gold_price_sar_karats()
    return LiveGoldPriceResponse(
        currency="SAR",
        rate_24k_per_gram=rate_24k,
        karats=karats,
        price_usd_per_oz=usd_per_oz,
        updated_at=updated_at,
    )


@app.get("/api/gold-rate/live", tags=["Gold"], summary="Live Saudi gold rates by karat")
async def live_gold_rate_by_karat():
    """
    Returns live Saudi gold prices in SAR per gram for multiple karats.
    """
    karats, rate_24k, _, _ = await fetch_live_gold_price_sar_karats()
    return {
        "country": "Saudi Arabia",
        "currency": "SAR",
        "unit": "g",
        "conversion": "XAU/USD per oz -> USD per gram -> SAR per gram",
        "karats": karats,
        "rate24k": karats["24K"] if "24K" in karats else rate_24k,
    }


# ── Customer lookup ────────────────────────────────────────────────────────────

@app.get(
    "/customer/{emirates_id}",
    response_model=CustomerProfile,
    tags=["Customer"],
    summary="Get customer profile by Emirates ID",
)
async def get_customer(emirates_id: str):
    """Returns profile for a known Emirates ID (from dummy dataset)."""
    profile = get_customer_profile(emirates_id)
    if profile is None:
        raise HTTPException(
            status_code=404,
            detail=f"No customer found for Emirates ID: {emirates_id}",
        )
    return profile


@app.get(
    "/customer/{emirates_id}/loans",
    response_model=LoanHistoryOverview,
    tags=["Customer"],
    summary="Get loan history for an Emirates ID",
)
async def get_customer_loans(emirates_id: str):
    """Returns full loan history overview including active/closed loans."""
    profile = get_customer_profile(emirates_id)
    if profile is None:
        raise HTTPException(status_code=404, detail=f"Unknown Emirates ID: {emirates_id}")
    return get_loan_history(emirates_id)


# ── Gold history + prediction ──────────────────────────────────────────────────

@app.get(
    "/gold/insights",
    tags=["Gold"],
    summary="Historical prices + future prediction for a given tenure",
)
async def gold_insights(
    tenure_months: int = Query(default=12, ge=1, le=36, description="Loan tenure in months"),
):
    """
    Returns 6-month historical gold prices (AED/g) and a polynomial-regression
    forecast for the requested tenure.
    """
    insights = await build_gold_insights(tenure_months)
    return insights


# ── Main calculation endpoint ──────────────────────────────────────────────────

@app.post(
    "/loan/calculate",
    response_model=LoanCalculationResponse,
    tags=["Loan"],
    summary="Calculate LTV, loan eligibility, and risk for a gold loan application",
)
async def calculate_loan(req: LoanCalculationRequest):
    """
    Full pipeline:
    1. Fetch customer profile & loan history from Emirates ID
    2. Fetch live gold price
    3. Calculate gold valuation
    4. Compute LTV with all adjustment factors
    5. Predict gold price over the loan tenure
    6. Compute user & company risk scores
    7. Return a complete eligibility dashboard payload
    """

    # ── 1. Customer data ──────────────────────────────────────────────────────
    customer = get_customer_profile(req.emirates_id)
    if customer is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Emirates ID '{req.emirates_id}' not found in the system. "
                "Ensure seed_data.py has been run and the ID is correct."
            ),
        )
    history = get_loan_history(req.emirates_id)

    # ── 1b. Enrich with UAE PASS live identity (best-effort) ─────────────────
    uaepass = await fetch_uaepass_profile(req.emirates_id)
    if uaepass:
        customer = customer.model_copy(update={
            "customer_name": uaepass.get("fullnameEN") or customer.customer_name,
            "nationality":   uaepass.get("nationalityEN") or customer.nationality,
            "mobile":        uaepass.get("mobile") or customer.mobile,
            "gender":        uaepass.get("gender"),
            "email":         uaepass.get("email"),
            "full_name_ar":  uaepass.get("fullnameAR"),
            "nationality_ar": uaepass.get("nationalityAR"),
            "uaepass_verified": True,
        })

    # ── 2. Live SAR karat rates (same source used by /api/gold-rate/live) ─────
    live_karats, _, _, _ = await fetch_live_gold_price_sar_karats()

    # ── 3. Gold insights (live AED price + history + prediction) ───────────────
    gold_insights = await build_gold_insights(req.tenure_months.value)

    # ── 4 & 5. LTV + eligibility calculation ─────────────────────────────────
    calc = calculate_ltv_and_loan(
        carat=req.carat,
        gold_weight_grams=req.gold_weight_grams,
        tenure_months=req.tenure_months.value,
        job_profession=req.job_profession,
        customer=customer,
        loan_history=history,
        gold_insights=gold_insights,
    )

    # ── 6. Risk analysis ──────────────────────────────────────────────────────
    risk = build_risk_insights(
        customer=customer,
        history=history,
        gold_insights=gold_insights,
        job_profession=req.job_profession.value,
        eligible_loan_aed=calc["eligible_loan_amount_aed"],
        ltv_pct=calc["recommended_ltv_pct"],
        tenure_months=req.tenure_months.value,
    )

    # ── 7. Assemble response ──────────────────────────────────────────────────
    return LoanCalculationResponse(
        **calc,
        customer_profile=customer,
        loan_history=history,
        gold_insights=gold_insights,
        risk_insights=risk,
        live_gold_currency="SAR",
        live_gold_rates=live_karats,
    )


# ── Dev runner ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
