"""
services/customer_service.py

Loads customer and loan data from the JSON files generated by seed_data.py.
In production this would query a real database / KYC service.
"""

import json
from pathlib import Path
from typing import Optional

from models import (
    CustomerProfile, LoanHistoryItem, LoanHistoryOverview,
    LoanStatus, RiskCategory,
)

DATA_DIR = Path(__file__).parent.parent / "data"

# ── Load once at import time ───────────────────────────────────────────────────

def _load_json(name: str) -> dict:
    path = DATA_DIR / name
    if not path.exists():
        raise RuntimeError(
            f"Data file '{name}' not found. "
            "Please run  python seed_data.py  first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


_customers: dict = {}
_loans: dict     = {}


def _ensure_loaded():
    global _customers, _loans
    if not _customers:
        _customers = _load_json("dummy_customers.json")
    if not _loans:
        _loans = _load_json("dummy_loans.json")


# ── Public helpers ─────────────────────────────────────────────────────────────

def get_customer_profile(emirates_id: str) -> Optional[CustomerProfile]:
    _ensure_loaded()
    raw = _customers.get(emirates_id)
    if raw is None:
        return None
    return CustomerProfile(
        customer_name=raw["customer_name"],
        emirates_id=raw["emirates_id"],
        nationality=raw["nationality"],
        mobile=raw["mobile"],
        customer_type=raw["customer_type"],
        risk_category=RiskCategory(raw["risk_category"]),
        cibil_score=raw["cibil_score"],
    )


def get_loan_history(emirates_id: str) -> LoanHistoryOverview:
    _ensure_loaded()
    raw_loans = _loans.get(emirates_id, [])

    items: list[LoanHistoryItem] = []
    for l in raw_loans:
        items.append(LoanHistoryItem(
            loan_id=l["loan_id"],
            tenure_months=l["tenure_months"],
            status=LoanStatus(l["status"]),
            missed_emis=l["missed_emis"],
            amount=l["amount"],
            outstanding_balance=l["outstanding_balance"],
        ))

    active_loans = [x for x in items if x.status == LoanStatus.ACTIVE]
    closed_loans = [x for x in items if x.status == LoanStatus.CLOSED]
    total_missed = sum(x.missed_emis for x in items)
    outstanding  = sum(x.outstanding_balance for x in active_loans)

    return LoanHistoryOverview(
        total_previous=len(items),
        active_loans=len(active_loans),
        closed_loans=len(closed_loans),
        missed_emis=total_missed,
        outstanding_balance=round(outstanding, 2),
        loan_items=items,
    )
